Update Agent postinst
This also fixes a typo where devolutions-agent.service was accidentally called
rp.service.

diff --git a/package/AgentLinux/agent/debian/postinst b/package/AgentLinux/agent/debian/postinst
--- a/package/AgentLinux/agent/debian/postinst
+++ b/package/AgentLinux/agent/debian/postinst
@@ -11,14 +11,32 @@ fi
 
 set -e
 # Automatically added by dh_installsystemd/13.18ubuntu2.1
-if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
-	systemctl --system daemon-reload >/dev/null || true
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	# The following line should be removed in trixie or trixie+1
+	deb-systemd-helper unmask 'devolutions-agent.service' >/dev/null || true
+
+	# was-enabled defaults to true, so new installations run enable.
+	if deb-systemd-helper --quiet was-enabled 'devolutions-agent.service'; then
+		# Enables the unit on first installation, creates new
+		# symlinks on upgrades if the unit file has changed.
+		deb-systemd-helper enable 'devolutions-agent.service' >/dev/null || true
+	else
+		# Update the statefile to add new symlinks (if any), which need to be
+		# cleaned up on purge. Also remove old symlinks.
+		deb-systemd-helper update-state 'devolutions-agent.service' >/dev/null || true
+	fi
 fi
 # End automatically added section
 # Automatically added by dh_installsystemd/13.18ubuntu2.1
-if [ "$1" = "purge" ]; then
-	if [ -x "/usr/bin/deb-systemd-helper" ]; then
-		deb-systemd-helper purge 'rp.service' >/dev/null || true
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -z "${DPKG_ROOT:-}" ] && [ -d /run/systemd/system ]; then
+		systemctl --system daemon-reload >/dev/null || true
+		if [ -n "$2" ]; then
+			_dh_action=restart
+		else
+			_dh_action=start
+		fi
+		deb-systemd-invoke $_dh_action 'devolutions-agent.service' >/dev/null || true
 	fi
 fi
 # End automatically added section
