devolutions-gateway: uncomment release steps, set release conditions

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -26,6 +26,17 @@ jobs:
         run: |
           $RunJson = gh api /repos/devolutions/devolutions-gateway/actions/runs/${{ github.event.inputs.run-id }}
           $Run = $RunJson | ConvertFrom-Json
+
+          if ($($Run.head_branch) -Ne "master") {
+            echo "::error::specified run is not on master, exiting..."
+            exit 1
+          }
+
+          if (($($Run.status) -Ne "completed") -Or ($($Run.conclusion) -Ne "success")) {
+            echo "::error::specified run is either not complete or not successful, exiting..."            
+            exit 1
+          }
+
           echo "::set-output name=commit::$($Run.head_sha)"
 
       - name: Checkout ${{ github.repository }}
@@ -180,7 +191,7 @@ jobs:
         working-directory: ${{ steps.move-artifacts.outputs.package-path }}
         run: |
           echo ${{ secrets.DOCKER_HUB_BOT_PASSWORD }} | docker login -u devolutionsbot --password-stdin
-          # docker push ${{ steps.build-container.outputs.image-name }}
+          docker push ${{ steps.build-container.outputs.image-name }}
 
   github-release:
     name: GitHub release
@@ -203,7 +214,7 @@ jobs:
           $Files | % { "$($_.Hash)  $(Split-Path $_.Path -leaf)" } | Out-File -FilePath $HashPath -Append -Encoding ASCII
 
           $GhCmd = $(@('gh', 'release', 'create', "v$Version", $HashPath) + $Files.Path) -Join ' '
-          # Invoke-Expression @GhCmd
+          Invoke-Expression @GhCmd
 
   psgallery-release:
     name: PowerShell release
@@ -225,4 +236,4 @@ jobs:
           $Archive = Get-ChildItem -Recurse -Filter "*-ps-*.zip" -File -Path $StagingPath
           $Module = Join-Path $StagingPath PowerShell
           Expand-Archive -Path $Archive -DestinationPath $Module
-          # Publish-Module -Force -Path (Join-Path $Module DevolutionsGateway) -NugetApiKey "${{ secrets.PS_GALLERY_NUGET_API_KEY }}"
+          Publish-Module -Force -Path (Join-Path $Module DevolutionsGateway) -NugetApiKey "${{ secrets.PS_GALLERY_NUGET_API_KEY }}"
